version: '3'
networks:
    mongo-network:
      driver: bridge
      ipam:
        config:
            - subnet: 10.0.0.0/16
services:
  mongo1:
    image: mongo:4.0.4
    expose:
      - "27017"
    volumes:
      - C:/Users/user/Desktop/MongoCluster/Shard1/scripts/mongorc.js:/etc/mongorc.js
    networks:
        mongo-network:
            ipv4_address: 10.0.0.20
    command: mongod --replSet rs --bind_ip_all
  mongo2:
    image: mongo:4.0.4
    expose:
      - "27017"
    volumes:
      - C:/Users/user/Desktop/MongoCluster/Shard1/scripts/mongorc.js:/etc/mongorc.js
    networks:
        mongo-network:
            ipv4_address: 10.0.0.21
    command: mongod --replSet rs --bind_ip_all
  mongo3:
    image: mongo:4.0.4
    expose:
      - "27017"
    volumes:
      - C:/Users/user/Desktop/MongoCluster/Shard1/scripts/mongorc.js:/etc/mongorc.js
    networks:
        mongo-network:
            ipv4_address: 10.0.0.22
    command: mongod --replSet rs --bind_ip_all
  mongo-replica:
    image: mongo:4.0.4
    depends_on:
        - mongo1
        - mongo2
        - mongo3
    volumes:
        - C:/Users/user/Desktop/MongoCluster/Shard1/scripts/mongo_setup.sh:/scripts/mongo_setup.sh
    networks:
        mongo-network:
            ipv4_address: 10.0.0.10
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]